name: Build and Push webrtc-connect (Production Workflow)

# Run on push to main branch after testing is complete
on:
  push:
    branches:
      - main
    paths:
      - sleap_webRTC/** # Only run on changes to sleap_webRTC
      - .github/workflows/sleap_webrtc_production.yml # Only run on changes to this workflow


jobs:
  build:
    runs-on: ubuntu-latest # Only build on Ubuntu for now since Docker is not available on macOS runners
    strategy:
      matrix:
        platform: [linux/amd64] # Only build amd64 for now
      max-parallel: 2  # Build both architectures in parallel (if more than one)
    outputs:
      git_sha: ${{ steps.get_sha.outputs.sha }}
      sanitized_platform: ${{ steps.sanitize_platform.outputs.sanitized_platform }}
    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Get Git SHA
        id: get_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Debug Git SHA
        run: echo "Git SHA ${{ steps.get_sha.outputs.sha }}"

      # Generate a sanitized platform string with slashes replaced by dashes
      - name: Sanitize platform name
        id: sanitize_platform
        run: |
          sanitized_platform="${{ matrix.platform }}" # Copy platform value
          sanitized_platform="${sanitized_platform/\//-}" # Replace / with -
          echo "sanitized_platform=$sanitized_platform" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container # Use a container driver for Buildx (default)
          
      # Authenticate to GitHub Container Registry
      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and push the Docker image to GitHub Container Registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./sleap_webRTC/webRTC_worker_container # Build context wrt the root of the repository
          file: ./sleap_webRTC/webRTC_worker_container/Dockerfile # Path to Dockerfile wrt the root of the repository
          platforms: ${{ matrix.platform }}
          push: true # Push the image to GitHub Container Registry
          tags: |
            ghcr.io/${{ github.repository_owner }}/webrtc-connect:latest
            ghcr.io/${{ github.repository_owner }}/webrtc-connect:${{ steps.sanitize_platform.outputs.sanitized_platform }}
            ghcr.io/${{ github.repository_owner }}/webrtc-connect:${{ steps.sanitize_platform.outputs.sanitized_platform }}-nvidia-cuda-11.3.1-cudnn8-runtime-ubuntu20.04
            ghcr.io/${{ github.repository_owner }}/webrtc-connect:${{ steps.sanitize_platform.outputs.sanitized_platform }}-${{ steps.get_sha.outputs.sha }}
